
# Automatically generated by /Users/mshafae/github/cpsc120/cpsc-120-solution-lab-11/.action/ccsrcutilities.py on 2026-04-11 15:22:20

TARGET = hilo
# C++ Source Code Files
CXXFILES = hilo.cc hilo_functions.cc 
# C++ Headers Files
HEADERS = hilo_functions.h rng.h

DO_UNITTESTS = "True"

CXX = clang++
CXXFLAGS += -x c++ -g -O3 -Wall -pedantic -pipe -std=c++20
LDFLAGS += -g -O3 -Wall -pedantic -pipe -std=c++20

UNAME_S = $(shell uname -s)
ifeq ($(UNAME_S),Linux)
	CXXFLAGS += -D LINUX
	LDFLAGS += 
	SED = sed
	GTESTINCLUDE = -D LINUX
	GTESTLIBS = -L /usr/lib/gcc/x86_64-linux-gnu/11 -lgtest -lgtest_main -lpthread
endif
ifeq ($(UNAME_S),Darwin)
	ifeq (,$(wildcard "/opt/local/bin/port"))
		# Use MacPorts clang++'s standard library
		CXXFLAGS += -D OSX
		LDFLAGS += 
		SED = gsed
		GTESTINCLUDE = -I /opt/local/include -I /opt/local/src/googletest
		GTESTLIBS = -L /opt/local/libexec/llvm-18/lib/libc++ -L /opt/local/libexec/llvm-18/lib -L /opt/local/libexec/llvm-18/lib/libunwind -L /opt/local/lib -lgtest -lgtest_main -lunwind -rpath /opt/local/libexec/llvm-18/lib/libc++ -rpath /opt/local/libexec/llvm-18/lib/libunwind
	else
		# Use Apple's standard library (not recommended)
		CXXFLAGS += -D OSX
	endif
endif
UNAME_M = $(shell uname -m)
ifeq ($(UNAME_M),x86_64)
	CXXFLAGS += -D AMD64
endif
ifneq ($(filter %86,$(UNAME_M)),)
	CXXFLAGS += -D IA32
endif
ifneq ($(filter arm%,$(UNAME_M)),)
	CXXFLAGS += -D ARM
endif

GTEST_UNITTEST_BIN = part_unittest
GTEST_OUTPUT_FORMAT ?= "json"
GTEST_OUTPUT_FILE ?= "test_detail.json"

DOXYGEN = doxygen
DOCDIR = doc

MAKEHEADERS := $(shell command -v makeheaders 2>/dev/null)

OBJECTS = $(CXXFILES:.cc=.o)

DEP = $(CXXFILES:.cc=.d)

MKFILE_PATH := $(abspath $(lastword $(MAKEFILE_LIST)))
PART_PATH := $(dir $(MKFILE_PATH))
LAB_PART := $(notdir $(patsubst %/,%,$(dir $(MKFILE_PATH))))

.SILENT: doc lint format authors test
.PHONY: doc lint format authors clean spotless

default all: $(TARGET)

$(TARGET): $(OBJECTS)
	$(CXX) $(LDFLAGS) -o $(TARGET) $(OBJECTS) $(LLDLIBS)

# %.d: %.cc
# 	set -e; $(CXX) -Wall -MM $(CXXFLAGS) $<  > $@; [ -s $@ ] || rm -f $@

%.o: %.cc
	$(CXX) $(CXXFLAGS) -c $< -o $@ -MMD -MP

clean:
	-rm -f $(OBJECTS) core $(TARGET).core

spotless: clean cleanunittest
	-rm -f $(TARGET) $(DEP) a.out
	-rm -rf $(DOCDIR)
	-rm -rf $(TARGET).dSYM
	-rm -f compile_commands.json

doc: $(CXXFILES) $(HEADERS)
	(cat Doxyfile; echo "PROJECT_NAME = $(TARGET)") | $(DOXYGEN) -

compilecmd:
	@echo "$(CXX) $(CXXFLAGS)"

format:
	@python3 ../.action/checks.py format $(LAB_PART)

lint:
	@python3 ../.action/checks.py lint $(LAB_PART)

authors:
	@python3 ../.action/checks.py authors $(LAB_PART)

test:
	@python3 ../.config/system_test.py $(LAB_PART) $(TARGET)

ifneq ($(DO_UNITTESTS), "True")
unittest:
	@echo "No unit tests for $(LAB_PART)"
else
unittest: utest

utest: part_unittest
	@./$(GTEST_UNITTEST_BIN) --gtest_output=$(GTEST_OUTPUT_FORMAT):$(GTEST_OUTPUT_FILE)

$(TARGET)_unittest.o: $(TARGET)_unittest.cc
	@$(CXX) $(CXXFLAGS) -c $(GTESTINCLUDE) $<

part_unittest: $(TARGET)_functions.o $(TARGET)_unittest.o
	@$(CXX) $(LDFLAGS) -o $(GTEST_UNITTEST_BIN) $(TARGET)_unittest.o $(TARGET)_functions.o $(GTESTLIBS)


endif

cleanunittest:
	-@rm -rf part_unittest.dSYM $(TARGET)_unittest.o > /dev/null 2>&1 || true
	-@rm part_unittest test_detail.json > /dev/null 2>&1 || true

-include $(DEP)

